CREATE TABLE [dbo].[CustomerEquipmentActivities]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Country] NVARCHAR(100) NOT NULL, 
    [Customer] NVARCHAR(200) NOT NULL, 
    [ServiceEngineer] NVARCHAR(200) NOT NULL, 
    [ReportNumber] NVARCHAR(50) NULL, 
    [PreviousServiceDate] DATETIME NOT NULL, 
    [CurrentServiceDate] DATETIME NOT NULL, 
    [ReportDate] DATETIME NOT NULL, 
    [Equipment] NVARCHAR(50) NOT NULL, 
    [SiteLocation] NVARCHAR(100) NULL, 
    [DecanterModel] NVARCHAR(100) NULL, 
    [DecanterSerialNumber] NVARCHAR(100) NOT NULL, 
    [BowlSerialNumber] NVARCHAR(100) NULL, 
    [CustomerReference] NVARCHAR(100) NULL, 
    [RunningHours] INT NOT NULL, 
    [Controller] NVARCHAR(50) NOT NULL, 
    [HmiModel] NVARCHAR(50) NOT NULL, 
    [HmiSwVersion] NVARCHAR(50) NOT NULL, 
    [CpuModel] NVARCHAR(50) NOT NULL, 
    [CpuSwVersion] NVARCHAR(50) NOT NULL, 
    [ScopeOfWrok] NVARCHAR(50) NOT NULL, 
    [ScoperOfWorkOthers] NVARCHAR(50) NULL, 
    [WorkStatus] NVARCHAR(50) NOT NULL, 
    [DecanterStatus] NVARCHAR(50) NOT NULL, 
    [ReportGuid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [ReportType] NVARCHAR(100) NULL
)
